<a href="https://colab.research.google.com/github/PosgradoMNA/Atividades-de-aprendizaje-SamaraGarcia/blob/main/Assignment03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Actividad 4 Python Samara García González A0123001


**Asigment Python for Data Science**


**Módulo 5**

---



In [ ]:
#Módulo5: Learning Objectives
#Explain the use of the HTTP protocol using the Requests Library method
#Describe how the URL Request Response HTTP protocol works
#Learn to apply simple, open-source APIs
#Perform basic webscraping using Python
#Work with different file formats using Python
#Explain the difference between APIs and REST APIs
#Summarize how APIs receive and send information

In [2]:
import numpy as np
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [3]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

**Lab - Working with 1D Numpy Arrays **

In [5]:
#Creando una lista en python
b =  ["0", 1, "dos", "3", 4]

In [6]:
#Imprimiendo cada uno de los elementos
print("b[0]: ", b[0])
print("b[1]: ", b[1])
print("b[2]: ", b[2])
print("b[3]: ", b[3])
print("b[4]: ", b[4])

b[0]:  0
b[1]:  1
b[2]:  dos
b[3]:  3
b[4]:  4


In [7]:
#Creando un array de numpy 

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [8]:
#Imprimiendo cada elemento 
print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [9]:
#Verificando la versión de numpy que tenemos 
print(np.__version__)

1.21.6


In [10]:
#Verificando el tipo de valor que está guardado en a

type(a)

numpy.ndarray

In [11]:
#Verificando el tipo de valor que estan guardados en a 
a.dtype

dtype('int64')

Assigning a value

---



In [12]:
#Cambiando el valor de un elemento del array 
a[0] = 100
a

array([100,   1,   2,   3,   4])

In [13]:
#Cambiando el valor de un elemento del array 
a[3] = 300
a

array([100,   1,   2, 300,   4])

In [17]:
a = np.array([10, 2, 30, 40,50])
a[1]=20
a
# Cambia el segundo valor por 20


array([10, 20, 30, 40, 50])

Slicing

---



In [16]:
#Slicing a en d
d = a[1:4]
d

array([20, 30, 40])

In [19]:
#Definir los pasos del slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [21]:
#Si no se coloca la posición de inicio se considera como 0
print(arr[:4])

[1 2 3 4]


In [22]:
#Si no se coloca la posición de final se considera como length
print(arr[1:])

[2 3 4 5 6 7]


In [24]:
#Imprimer los  elementos pares  del array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])

[2 4 6 8]


**Asignando valores con list**

In [30]:
#Creando la lista de indexes
select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [29]:
#Usando una lista para seleccionar elementos
d = a[select]
d

array([100000, 100000, 100000, 100000])

In [28]:
a[select] = 100000
a

array([100000,     20, 100000, 100000, 100000])

Otros atributos

---



In [31]:
#Creandi un array con numpy
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [32]:
#Usando size
a.size

5

In [33]:
#Obtener el numero de dimensiones de un array numpy
a.size

5

In [34]:
#Obteniendo shape
a.shape

(5,)

In [35]:
#Obteniendo size, dimensions and shape
b = np.array([10, 20, 30, 40, 50, 60, 70])
b.size
b.ndim
b.shape

(7,)

Numpy Statistical Functions

---



In [42]:
# Create el array numpy
a = np.array([1, -1, 1, -1])

In [43]:
#Obteniendo la media
mean = a.mean()
mean

0.0

In [44]:
#Obteniendo la desviación estándar
standard_deviation=a.std()
standard_deviation

1.0

In [45]:
# Creando un array
b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [46]:
# Encontrando el valor máximo
max_b = b.max()
max_b

5

In [47]:
# Encontrando el valor minimo
min_b = b.min()
min_b

-1

In [49]:
#Encontrando la suma del máximo y el minimo
c = np.array([-10, 201, 43, 94, 502])
max_c = c.max()
max_c    
min_c = c.min()
min_c 
Sum = (max_c +min_c)
Sum

492

Numpy Array Operations

---

